# Generated by Django 5.0.1 on 2024-02-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pusher_app', '0002_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_secret_token', models.CharField(max_length=50)),
                ('data', models.JSONField()),
            ],
        ),
    ]
